=== salomvary/trains/elvira_spec/examples/station-list-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "number"
      },
      "isAlias": {
        "type": "boolean"
      },
      "name": {
        "type": "string"
      },
      "code": {
        "type": "string"
      },
      "baseCode": {
        "type": "string"
      },
      "isInternational": {
        "type": "boolean"
      },
      "canUseForOfferRequest": {
        "type": "boolean"
      },
      "canUseForPessengerInformation": {
        "type": "boolean"
      },
      "country": {
        "type": "string"
      },
      "coutryIso": {
        "type": "string"
      },
      "modalities": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "code": {
              "type": "number"
            },
            "name": {},
            "description": {},
            "order": {
              "type": "number"
            },
            "isDefault": {
              "type": "boolean"
            },
            "defaultColor": {
              "type": "string"
            },
            "inkColor": {
              "type": "string"
            },
            "sign": {
              "type": "object",
              "properties": {
                "fontName": {
                  "type": "string"
                },
                "character": {
                  "type": "string"
                }
              },
              "required": [
                "fontName",
                "character"
              ]
            },
            "foreignNames": {},
            "foreignDescriptions": {}
          },
          "required": [
            "code",
            "name",
            "description",
            "order",
            "isDefault",
            "defaultColor",
            "inkColor",
            "sign",
            "foreignNames",
            "foreignDescriptions"
          ]
        }
      },
      "nameWithoutComma": {
        "type": "string"
      },
      "isIn108_1": {
        "type": "boolean"
      }
    },
    "required": [
      "id",
      "isAlias",
      "name",
      "code",
      "baseCode",
      "isInternational",
      "canUseForOfferRequest",
      "canUseForPessengerInformation",
      "country",
      "coutryIso",
      "nameWithoutComma",
      "isIn108_1"
    ]
  }
}

=== salomvary/trains/elvira_spec/examples/station-list-shortened.json
[
  {
    "id": 7666,
    "isAlias": true,
    "name": "Bp (BUDAPEST*)",
    "code": "005510009",
    "baseCode": "3638",
    "isInternational": false,
    "canUseForOfferRequest": true,
    "canUseForPessengerInformation": false,
    "country": "Magyarország",
    "coutryIso": "HU",
    "modalities": [
      {
        "code": 100,
        "name": null,
        "description": null,
        "order": 0,
        "isDefault": false,
        "defaultColor": "#1C4281",
        "inkColor": "#FEFEFE",
        "sign": {
          "fontName": "/MAVI.MAVSTART.JE.Common;component/Resources/#MNR2007",
          "character": "ȧ"
        },
        "foreignNames": null,
        "foreignDescriptions": null
      }
    ],
    "nameWithoutComma": "",
    "isIn108_1": true
  },
  {
    "id": 257,
    "isAlias": false,
    "name": "BUDAPEST*",
    "code": "005510009",
    "baseCode": "3638",
    "isInternational": false,
    "canUseForOfferRequest": true,
    "canUseForPessengerInformation": false,
    "country": "Magyarország",
    "coutryIso": "HU",
    "modalities": [
      {
        "code": 100,
        "name": null,
        "description": null,
        "order": 0,
        "isDefault": false,
        "defaultColor": "#1C4281",
        "inkColor": "#FEFEFE",
        "sign": {
          "fontName": "/MAVI.MAVSTART.JE.Common;component/Resources/#MNR2007",
          "character": "ȧ"
        },
        "foreignNames": null,
        "foreignDescriptions": null
      }
    ],
    "nameWithoutComma": "BUDAPEST*",
    "isIn108_1": true
  }
]
